### ISSUE TITLE
Cant import data using sitetreeload

### ISSUE THREAD

**Issue by TitanFighter** [idlesign/django-sitetree#209]
I exported trees via `python manage.py sitetreedump > treedump.json`
Then dropped all tables, cleaned migrations, makemigrations, migrate.
Then tried to import treedump.json via `python manage.py sitetreeload treedump.json`

The 1st try:
```
Loading fixture from `treedump.json` ...
Traceback (most recent call last):
  File "/home/antonio/www/sportland/lib/python3.5/site-packages/django/core/serializers/json.py", line 79, in Deserializer
    objects = json.loads(stream_or_string)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/antonio/www/sportland/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/antonio/www/sportland/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/antonio/www/sportland/lib/python3.5/site-packages/django/core/management/base.py", line 305, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/antonio/www/sportland/lib/python3.5/site-packages/django/core/management/base.py", line 356, in execute
    output = self.handle(*args, **options)
  File "/home/antonio/www/sportland/lib/python3.5/site-packages/sitetree/management/commands/sitetreeload.py", line 109, in handle
    for obj in objects:
  File "/home/antonio/www/sportland/lib/python3.5/site-packages/django/core/serializers/json.py", line 86, in Deserializer
    six.reraise(DeserializationError, DeserializationError(e), sys.exc_info()[2])
  File "/home/antonio/www/sportland/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/antonio/www/sportland/lib/python3.5/site-packages/django/core/serializers/json.py", line 79, in Deserializer
    objects = json.loads(stream_or_string)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
django.core.serializers.base.DeserializationError: Expecting value: line 1 column 1 (char 0)
```
At the 1st line of the file I found `base dir path /home/antonio/www/sportland/sportland/src/sportland`. This was removed.

The 2nd try:
```
Loading fixture from `treedump.json` ...

Importing tree `top_menu` ...
Importing item `LogIn-SignUp` ...
Traceback (most recent call last):
  File "/home/antonio/www/sportland/lib/python3.5/site-packages/django/db/models/fields/related_descriptors.py", line 170, in __get__
    rel_obj = getattr(instance, self.cache_name)
AttributeError: 'TreeItem' object has no attribute '_parent_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/antonio/www/sportland/lib/python3.5/site-packages/sitetree/management/commands/sitetreeload.py", line 159, in handle
    tree_item.save(using=using)
  File "/home/antonio/www/sportland/lib/python3.5/site-packages/sitetree/models.py", line 133, in save
    if self.parent == self:
  File "/home/antonio/www/sportland/lib/python3.5/site-packages/django/db/models/fields/related_descriptors.py", line 179, in __get__
    rel_obj = qs.get()
  File "/home/antonio/www/sportland/lib/python3.5/site-packages/django/db/models/query.py", line 385, in get
    self.model._meta.object_name
sitetree.models.DoesNotExist: TreeItem matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/antonio/www/sportland/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/antonio/www/sportland/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/antonio/www/sportland/lib/python3.5/site-packages/django/core/management/base.py", line 305, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/antonio/www/sportland/lib/python3.5/site-packages/django/core/management/base.py", line 356, in execute
    output = self.handle(*args, **options)
  File "/home/antonio/www/sportland/lib/python3.5/site-packages/sitetree/management/commands/sitetreeload.py", line 186, in handle
    sys.exc_type, sys.exc_value, sys.exc_traceback
AttributeError: module 'sys' has no attribute 'exc_type'
```

The 3rd try:
The trees are manually recreated and exported. Trying to import and again see the same problems\errors.

Django 1.10
Ubuntu 16.04

Original dump attached (json changed to txt in order to upload it)
[treedump.txt](https://github.com/idlesign/django-sitetree/files/436008/treedump.txt)

**Comment by idlesign** [comment]
Thank you fpr the report.
That's on sitetree 1.6.0 I suppose?

**Comment by TitanFighter** [comment]
1.5.1 and 1.6.0

**Comment by idlesign** [comment]
Just pushed https://github.com/idlesign/django-sitetree/commit/ece31f64ae3fb5315a6d1c8d66be0001de83cfa6 wich should improve things.

Yet the very first line in `treedump.txt` shouldn't be there at all.

You can verify the fix using `master` branch.
And again, thank you for the report.

**Comment by idlesign** [comment]
Considered closed. 
Feel free to reopen if required.
